=== NataliaPalej/service-oriented-architect/Lec 2 - XML Schema Types/Lab 2.1 - Convert to inline/BookStore.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.books.org"
            xmlns="http://www.books.org"
            elementFormDefault="qualified">

    <xsd:element name="bookstore">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="book" minOccurs="1" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="title" type="xsd:string"/>
                            <xsd:element name="chapter" minOccurs="1" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="number" type="xsd:integer"/>
                                        <xsd:element name="title" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="price" minOccurs="1" maxOccurs="unbounded" type="xsd:double"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== NataliaPalej/service-oriented-architect/Lec 1 - SOA Introduction/Lab1 - XML Exercises/bookXS.xml
<?xml version="1.0"?>
<bookstore xmlns="http://www.books.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.books.org BookStore.xsd">
    <book>
        <title>Title 1</title>
        <chapter>
            <number>1</number>
            <title>Title 1 a</title>
        </chapter>
        <price>15.99</price>
    </book>

    <book>
        <title>Title 2</title>
        <chapter>
            <number>1</number>
            <title>Title 2 a</title>
        </chapter>
        <price>20.99</price>
    </book>
</bookstore>
